### ISSUE TITLE
WhateverGreen

### ISSUE THREAD

**Issue by johnnync13** [stevezhengshiqi/XiaoMi-Pro#1]
You should use Intelfb patcher to fix framebuffer
Serán my config.plist/Devices/Properties
https://github.com/johnnync13/XiaoMi-Pro

https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-for-mojave.256490/

**Comment by stevezhengshiqi** [comment]
Thanks a lot. The instruction is very useful.
Well, since current Clover patch method is available on both High Sierra and Mojave, and I suffered from VRAM 7mb after using the parameters in your config.plist/Devices/Properties(10.13.6), I may keep using KextsToPatch for a moment.

I see a lot potential in `WhateverGreen.kext`. Because it's still in beta version, I may wait until this kext is stable enough.

**Comment by johnnync13** [comment]
Yes, of course. This patch send me another member, and It is not correct but It is an example. In my laptop MSI, I get 2048 MB on VRAM.

**Comment by stevezhengshiqi** [comment]
I think the actual VRAM is still 1536MB. After increased from 1536MB to 2048MB, the OpenGL score in `CineBench R15` doesn't change. 
By the way, I patched `config.plist` in the latest two commits, thank you for instruction.
