### ISSUE TITLE
 it's not a issue, it's a doubt

### ISSUE THREAD

**Issue by johnnync13** [stevezhengshiqi/XiaoMi-Pro#3]
Would you please tell me how do you make pcilist.aml and uiac? I need create this for my xiaomi mi notebook 12'5

**Comment by stevezhengshiqi** [comment]
Sure, but I don't know whether I can explain clearly here. I don't think xiaomi mi notebook 12'5 has more than 15 ports, so maybe it doesn't need a `SSDT-UIAC`. A `SSDT-USBX.aml` is enough.
The complete instruction is at [here](https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/).

For SSDT-PCIList.aml, first you have to check the devices that under PCI0 root in IORegistryExplorer. For example, mine has these devices:
![screen shot 2018-08-03 at 00 12 18](https://user-images.githubusercontent.com/36894554/43596494-0d123d70-96b2-11e8-87db-1c4eda407ef2.jpg) For each one, you can write a `_DSM` method in` SSDT-PCIList.aml`. `LPCB` and `XHC` don't need `_DSM` methods because they already have one in `SSDT-LPC.aml` and `SSDT-XHC.aml`.

**Comment by johnnync13** [comment]
Thank you for all.. But I don't undestand what information I have to put on PCIList.
How I take the reference or ID for each device?

**Comment by stevezhengshiqi** [comment]
I use `PCI-Z` in Windows to check my PCI information. 
HINT: If you directly edit the aml file, notice the value behind `Buffer`. It should be adjusted to fit the size of the information below.

For the trackpad, I noticed that 12'5 has Synapitcs trackpad, which is not perfectly supported by `VoodooI2C`. You can try to change PIN value under TPD0 device (TPD1) to see whether works or not.

**Comment by johnnync13** [comment]
I need your help to patch pcilist.
This is my information. It is similar than notebook pro.
[ioreg.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2372943/ioreg.zip)

![pci](https://user-images.githubusercontent.com/22727137/45391330-d1cfcd00-b622-11e8-9c6b-08f30d89c8cd.png)
<img width="960" alt="pci" src="https://user-images.githubusercontent.com/22727137/45391230-7ac9f800-b622-11e8-969c-3e5acd69d58a.png">
[Info hackintosh.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2372926/Info.hackintosh.zip)

**Comment by stevezhengshiqi** [comment]
Hi, it's indeed similar with Xiaomi Pro's PCI Information. I don't know the sound card model of your device, and I take it as ALC298. You can modify the model name after you know the sound card model.
[SSDT-PCIList.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2372990/SSDT-PCIList.zip)

**Comment by johnnync13** [comment]
I use applehda for show information...
![applehda](https://user-images.githubusercontent.com/22727137/45392468-c7640200-b627-11e8-80c8-8b34cb1bd38c.png)

**Comment by stevezhengshiqi** [comment]
Changed model HDEF name from ALC298 to ALC255.
[SSDT-PCIList.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2373092/SSDT-PCIList.zip)
